---
title: "Data Exploration"
author: "Lidio Jaimes Jr"
date: "2024-10-21"
output: pdf_document
---
```{r Importing libraries}
library(tidyverse)
```

```{r Reading in Data}
stroke_raw <- 
  readxl::read_xlsx("Capstone Combined Data Collection Sheets - Summer 2024.xlsx", 
                    skip = 1) |> 
  janitor::clean_names()
stroke <- stroke_raw[-c(1,376), ] #get rid of dictionary and black row

# E336 (patient 333) and E340 (patient 337) have full date instead of just year
stroke[stroke$id_number == 333, "year_of_birth"] = 1905 #set as 1981 instead of 1905
stroke[stroke$id_number == 337, "year_of_birth"] = 1942
stroke$date_identified = openxlsx::convertToDate(stroke$date_identified)
stroke$date_of_stroke = openxlsx::convertToDate(stroke$date_of_stroke)

#Patients 211, 391 (repeat MRN), 528, 529, 536, 537, 555, 558, 576, 582
stroke <- 
  stroke |> 
  filter(!id_number%in%c(211, 391, 528, 529, 536, 537, 555, 558, 576, 582),
         ischemic == 1) #focus on ischemic
```

Not sure about error message regarding *Expiration Date* may be because of duplicate rownames. There are two duplicate columns for expiration date 97 and 173

```{r}
stroke |> 
  select(id_number,location_of_stroke,cortical_location_if_applicable)
```

They need to move row 3 for "Lesion Location" section to row 2. Location of stroke variable doesn't tell us anything in R, has a 1 if they had it in the brainstem, 0 otherwise. Could use the case_when to make the factor variable

```{r}
# stroke |> 
#   mutate(location_of_stroke = case_when(
#     brainstem == 1 ~ "brainstem",
#     cerebellum == 1 ~ "cerebellum"
#     cortical == 1 ~ "cortical",
#     subcortical == 1 ~ "subcortical",
#     other == 1 ~ "other"
#   ))
```

